



type MutationRoot {
	addDownload(url: String!): Boolean!
}

type QueryRoot {
	greet(name: String!): String!
}


type SubscriptionRoot {
	getDownloads: Boolean!
}

schema {
	query: QueryRoot
	mutation: MutationRoot
	subscription: SubscriptionRoot
}
