



type Model {
	id: Int!
	fileName: String!
	host: String!
	url: String!
	status: String!
	rawSize: Float!
	adjustedSize: Float!
	byteUnit: String!
	progress: String!
	tempFile: String!
}

type QueryRoot {
	livenessProbe: Boolean!
	getDownloads: [Model!]!
}


schema {
	query: QueryRoot
}
