



type Model {
	id: Int!
	name: String!
	rawSize: String!
	adjustedSize: String!
	unit: String!
	url: String!
	host: String!
}

type MutationRoot {
	addDownload(url: String!): Boolean!
}

type QueryRoot {
	greet(name: String!): String!
	downloads: [Model!]!
	startDownloads: String!
	pauseDownloads: String!
	stopDownloads: String!
}


type SubscriptionRoot {
	integers(step: Int! = 1): Int!
}

schema {
	query: QueryRoot
	mutation: MutationRoot
	subscription: SubscriptionRoot
}
